// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.betterminds.model;

import br.com.betterminds.model.Endereco;
import br.com.betterminds.model.EnderecoDataOnDemand;
import br.com.betterminds.model.EnderecoIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EnderecoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EnderecoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EnderecoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EnderecoIntegrationTest: @Transactional;
    
    @Autowired
    EnderecoDataOnDemand EnderecoIntegrationTest.dod;
    
    @Test
    public void EnderecoIntegrationTest.testCountEnderecoes() {
        Assert.assertNotNull("Data on demand for 'Endereco' failed to initialize correctly", dod.getRandomEndereco());
        long count = Endereco.countEnderecoes();
        Assert.assertTrue("Counter for 'Endereco' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EnderecoIntegrationTest.testFindEndereco() {
        Endereco obj = dod.getRandomEndereco();
        Assert.assertNotNull("Data on demand for 'Endereco' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Endereco' failed to provide an identifier", id);
        obj = Endereco.findEndereco(id);
        Assert.assertNotNull("Find method for 'Endereco' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Endereco' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EnderecoIntegrationTest.testFindAllEnderecoes() {
        Assert.assertNotNull("Data on demand for 'Endereco' failed to initialize correctly", dod.getRandomEndereco());
        long count = Endereco.countEnderecoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Endereco', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Endereco> result = Endereco.findAllEnderecoes();
        Assert.assertNotNull("Find all method for 'Endereco' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Endereco' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EnderecoIntegrationTest.testFindEnderecoEntries() {
        Assert.assertNotNull("Data on demand for 'Endereco' failed to initialize correctly", dod.getRandomEndereco());
        long count = Endereco.countEnderecoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Endereco> result = Endereco.findEnderecoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Endereco' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Endereco' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EnderecoIntegrationTest.testFlush() {
        Endereco obj = dod.getRandomEndereco();
        Assert.assertNotNull("Data on demand for 'Endereco' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Endereco' failed to provide an identifier", id);
        obj = Endereco.findEndereco(id);
        Assert.assertNotNull("Find method for 'Endereco' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEndereco(obj);
        Integer currentVersion = obj.getVersao();
        obj.flush();
        Assert.assertTrue("Version for 'Endereco' failed to increment on flush directive", (currentVersion != null && obj.getVersao() > currentVersion) || !modified);
    }
    
    @Test
    public void EnderecoIntegrationTest.testMergeUpdate() {
        Endereco obj = dod.getRandomEndereco();
        Assert.assertNotNull("Data on demand for 'Endereco' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Endereco' failed to provide an identifier", id);
        obj = Endereco.findEndereco(id);
        boolean modified =  dod.modifyEndereco(obj);
        Integer currentVersion = obj.getVersao();
        Endereco merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Endereco' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersao() > currentVersion) || !modified);
    }
    
    @Test
    public void EnderecoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Endereco' failed to initialize correctly", dod.getRandomEndereco());
        Endereco obj = dod.getNewTransientEndereco(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Endereco' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Endereco' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Endereco' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EnderecoIntegrationTest.testRemove() {
        Endereco obj = dod.getRandomEndereco();
        Assert.assertNotNull("Data on demand for 'Endereco' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Endereco' failed to provide an identifier", id);
        obj = Endereco.findEndereco(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Endereco' with identifier '" + id + "'", Endereco.findEndereco(id));
    }
    
}
