// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.betterminds.model;

import br.com.betterminds.model.Pessoa;
import br.com.betterminds.model.PessoaDataOnDemand;
import br.com.betterminds.model.PessoaIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PessoaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PessoaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PessoaIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PessoaIntegrationTest: @Transactional;
    
    @Autowired
    PessoaDataOnDemand PessoaIntegrationTest.dod;
    
    @Test
    public void PessoaIntegrationTest.testCountPessoas() {
        Assert.assertNotNull("Data on demand for 'Pessoa' failed to initialize correctly", dod.getRandomPessoa());
        long count = Pessoa.countPessoas();
        Assert.assertTrue("Counter for 'Pessoa' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PessoaIntegrationTest.testFindPessoa() {
        Pessoa obj = dod.getRandomPessoa();
        Assert.assertNotNull("Data on demand for 'Pessoa' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Pessoa' failed to provide an identifier", id);
        obj = Pessoa.findPessoa(id);
        Assert.assertNotNull("Find method for 'Pessoa' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Pessoa' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PessoaIntegrationTest.testFindAllPessoas() {
        Assert.assertNotNull("Data on demand for 'Pessoa' failed to initialize correctly", dod.getRandomPessoa());
        long count = Pessoa.countPessoas();
        Assert.assertTrue("Too expensive to perform a find all test for 'Pessoa', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Pessoa> result = Pessoa.findAllPessoas();
        Assert.assertNotNull("Find all method for 'Pessoa' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Pessoa' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PessoaIntegrationTest.testFindPessoaEntries() {
        Assert.assertNotNull("Data on demand for 'Pessoa' failed to initialize correctly", dod.getRandomPessoa());
        long count = Pessoa.countPessoas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Pessoa> result = Pessoa.findPessoaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Pessoa' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Pessoa' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PessoaIntegrationTest.testFlush() {
        Pessoa obj = dod.getRandomPessoa();
        Assert.assertNotNull("Data on demand for 'Pessoa' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Pessoa' failed to provide an identifier", id);
        obj = Pessoa.findPessoa(id);
        Assert.assertNotNull("Find method for 'Pessoa' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPessoa(obj);
        Integer currentVersion = obj.getVersao();
        obj.flush();
        Assert.assertTrue("Version for 'Pessoa' failed to increment on flush directive", (currentVersion != null && obj.getVersao() > currentVersion) || !modified);
    }
    
    @Test
    public void PessoaIntegrationTest.testMergeUpdate() {
        Pessoa obj = dod.getRandomPessoa();
        Assert.assertNotNull("Data on demand for 'Pessoa' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Pessoa' failed to provide an identifier", id);
        obj = Pessoa.findPessoa(id);
        boolean modified =  dod.modifyPessoa(obj);
        Integer currentVersion = obj.getVersao();
        Pessoa merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Pessoa' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersao() > currentVersion) || !modified);
    }
    
    @Test
    public void PessoaIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Pessoa' failed to initialize correctly", dod.getRandomPessoa());
        Pessoa obj = dod.getNewTransientPessoa(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Pessoa' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Pessoa' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Pessoa' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PessoaIntegrationTest.testRemove() {
        Pessoa obj = dod.getRandomPessoa();
        Assert.assertNotNull("Data on demand for 'Pessoa' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Pessoa' failed to provide an identifier", id);
        obj = Pessoa.findPessoa(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Pessoa' with identifier '" + id + "'", Pessoa.findPessoa(id));
    }
    
}
